### ISSUE TITLE
Magnet sensor leaks activity context

### ISSUE THREAD

**Issue by eleventigers** [googlesamples/cardboard-java#19]
According to this decompiled Cardboard SDK [source](https://github.com/raasun/cardboard/blob/master/src/com/google/vrtoolkit/cardboard/sensors/MagnetSensor.java), OnCardboardTriggerListener is never properly released. CardboardActivity registers as a listener however it does not remove itself onPause or onDestroy causing its context leak. Any ideas how to fix this?

**Comment by rsanchezsaez** [comment]
In case anybody cares @eleventigers fixed this on our newer SDK decompilation (https://github.com/rsanchezsaez/cardboard-java/commit/11a95bc8189a994568a8f8bc7b159026d46e0567).

**Comment by rahul27** [comment]
I noticed this issue on the sample app as well. The thread count associated with MagnetSensor.java increases every time I pause and resume the app.

**Comment by R1ck77** [comment]
As of now, the leak is still there (even though Google re-factored the code and moved `magneticSensor` into an instance of a `SensorConnector` class). I solved this problem (also thanks to your information) using reflection.

You can find my the solution here:

[Memory leak in CardboardActivity](http://stackoverflow.com/a/31038533/2177061)

Still, it would be good if the issue could be fixed in the codebase (it's an one-liner after all).

**Comment by dav-cz** [comment]
This should be fixed with v0.6. Thanks for the reports!

**Comment by sunjinbo** [comment]
@dav-cz where can I find v0.6?  Thank you!

**Comment by smdol** [comment]
That was the release back in January.  You can find it in the commit history here:

https://github.com/googlevr/gvr-android-sdk/commits/master

(There doesn't seem to be a tag for it.)
