### ISSUE TITLE
GPL v2/3 compatibility question

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-java#52]
There is an open source game engine based on Quake GPL source that wouldn't mind getting Google Cardboard SDK integrated. 

The developer raised concerns that SDK may not be GPL compatible. 

Could someone from Google clarify license stance and if SDK is compatible with GPL v2 or v3 ?

Thanks.

**Comment by smdol** [comment]
The Cardboard SDK license is Apache 2.0.

**Comment by motorsep** [comment]
From the developer of the engine: "The sdk is apache 2, but the GPL covers the entire work, including any libraries. You can do what you want with the headers Google provides, but that's not the source, and thus not compatible."

I am guessing he is talking about whatever comes in .jar with SDK or any libs that come in object form with SDK.

**Comment by nathanmartz** [comment]
Sorry, but we can't provide legal advice on whether the cardboard SDK is
compliant or not with the license of another product.

**Comment by R1ck77** [comment]
I'm not a lawyer and I'm not a developer, but this link might clarify the situation for you:

[What legal issues come up if I use GPL-incompatible libraries with GPL software?](http://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs)

If I understand it right (and, again, I might be getting it totally wrong!), you should ask the quake-like engine author for an exception to the license, in order to be able to integrate his/her code in your program.

Late answer, but this might be of some use to someone else.
